assets:
  css:
    - bundles/itklokalcentertemplate/assets/build/itklokalcentertemplate.min.css
  js_prod:
    - bundles/itklokalcentertemplate/assets/build/itklokalcentertemplate.min.js
modules:
  toolModule:
    files:
      - bundles/itklokalcentertemplate/apps/toolsModule/lokalcenter-touch-controller.js
      - bundles/itklokalcentertemplate/apps/toolsModule/lokalcenter-color-picker.js
      - bundles/itklokalcentertemplate/apps/toolsModule/lokalcenter-text.js
      - bundles/itklokalcentertemplate/apps/toolsModule/lokalcenter-quotes.js
apps:
