# Injecting tool into toolsModule, to make it
modules:
  toolModule:
    files:
      - bundles/itklokalcentertemplate/apps/toolsModule/lokalcenter-touch-controller.js
      - bundles/itklokalcentertemplate/apps/toolsModule/lokalcenter-color-picker.js
apps:
